version: '3.7'

services:
  sample-micro-service:
    build:
      context: ./sample-micro-service
    container_name: sample
    hostname: sample
    volumes:
      - ./sample-micro-service:/var/www
    networks:
      - sample_net

  nginx:
    build:
      context: sample-micro-service/nginx
    container_name: nginx
    volumes:
      - ./sample-micro-service:/var/www
      - ./sample-micro-service/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./sample-micro-service/nginx/sites/:/etc/nginx/sites-available
      - ./sample-micro-service/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - sample-micro-service
    networks:
      - sample_net

  fxproxy-for-sample-service:
    build:
      context: .docker
    container_name: fxproxy
    hostname: fxproxy
    ports:
      - '8888:8888'
      - '8000:8000'
    volumes:
      - .:/app
      - .docker/conf.yaml:/etc/fxproxy.yml
      - ./logs/fxproxy/:/var/log/
    depends_on:
      - nginx
    networks:
      - sample_net

networks:
  sample_net:
    ipam:
      driver: default
